
# -Dspring.profiles.active=



spring:
  profiles:
    group:
      local: local
      dev: dev
      prod: prod
    default: local
    active: ${TOKI-BACKEND-ACTIVE:local}
  config:
    import: "application-secret.yml"


logging:
  level:
    root: info
    org:
      apache: debug
      kurento: debug
      springframework: info
      AbstractHandshakeHandler: trace



#ssl key
server:
  ssl:
    enabled: true
    key-store: classpath:${KEY-PATH}
    key-store-password: ${KEY-PASS}
    key-store-type: PKCS12
    key-alias: ${KEY-ALIAS}