
# -Dspring.profiles.active=



spring:
  profiles:
    group:
      local: local
      dev: dev
      prod: prod
    default: local
    active: ${TOKI-BACKEND-ACTIVE:local}
  config:
    import: "application-secret.yml"



logging:
  level:
    web: debug


