
server:
  port: ${PORT}
spring:
  config:
    activate:
      on-profile: dev
  redis:
    host: ${REDISDB-HOST-DEV}
    password: ${REDISDB-PASSWORD-DEV}
    port: ${REDISDB-PORT-DEV}

  # Mysql Database 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://${MYSQLDB-URL}/${MYSQLDB-NAME-DEV}?useUnicode=true&serverTimezone=Asia/Seoul'
    username: ${MYSQLDB-NAME-DEV}
    password: ${MYSQLDB-PASSWORD-DEV}

  # JPA 설정
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update        # DB 테이블 전략 (none, create, create-drop, update, validate)
    properties:
      hibernate:
        format_sql: true      #
        show_sql: true        #



logging:
  level:
    web: debug
    sql: debug


